02 - Hello World MVC/02 - Hello World MVC/02 - Hello World MVC/Controllers/HelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _02___Hello_World_MVC.Controllers
{
    public class HelloController : Controller
    {
        // GET: Hello
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult saludo()
        {
            return View();
        }
    }
}

02 - Hello World MVC/02 - Hello World MVC/02 - Hello World MVC/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _02___Hello_World_MVC.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista()
        {
            return View();
        }
    }
}

02 - Hello World MVC/02 - Hello World MVC/02 - Hello World MVC/Views/Hello/saludo.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>saludo</title>
</head>
<body>
    @Html.ActionLink("Ir a la lista", "Lista", "Productos") <br />
    <div>
        Hola mundo, esto es una página to guapa
    </div>
</body>
</html>

02 - Hello World MVC/02 - Hello World MVC/02 - Hello World MVC/Views/Productos/index.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>index</title>
</head>
<body>
    <div>
        @Html.ActionLink("Ir a la lista", "Lista", "Productos", null) <br/>
        <a href="/Productos/lista">Click para ir a la lista</a>
    </div>
</body>
</html>

02 - Hello World MVC/02 - Hello World MVC/02 - Hello World MVC/Views/Productos/lista.cshtml
@model IEnumerable<_02___Hello_World_MVC.RouteConfig>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>lista</title>
</head>
<body>
    <ul style="list-style-type:square">
        <li>Coffee</li>
        <li>Tea</li>
        <li>Milk</li>
        <li>Nojeque</li>
        <li>Nojecuantos</li>
        <li>Buf</li>
    </ul>
</body>
</html>